# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 15:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20180504_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更改时间'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodscategory',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更改时间'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='goodscategorybrand',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更改时间'),
        ),
    ]
