# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-14 16:56
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180508_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': '首页轮播图', 'verbose_name_plural': '首页轮播图'},
        ),
        migrations.AlterModelOptions(
            name='goodsimage',
            options={'verbose_name': '商品轮播图', 'verbose_name_plural': '商品轮播图'},
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(help_text='商品类目', on_delete=django.db.models.deletion.CASCADE, to='goods.GoodsCategory', verbose_name='商品类目'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='click_num',
            field=models.IntegerField(default=0, help_text='点击数', verbose_name='点击数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='fav_num',
            field=models.IntegerField(default=0, help_text='收藏数', verbose_name='收藏数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_brief',
            field=models.TextField(help_text='商品简短描述', max_length=500, verbose_name='商品简短描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=DjangoUeditor.models.UEditorField(default='', help_text='商品详情', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_front_image',
            field=models.ImageField(blank=True, help_text='封面图', null=True, upload_to='goods/images/', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_num',
            field=models.IntegerField(default=0, help_text='库存数', verbose_name='库存数'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goods_sn',
            field=models.CharField(default='', help_text='商品唯一货号', max_length=50, verbose_name='商品唯一货号'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='是否热销', verbose_name='是否热销'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_new',
            field=models.BooleanField(default=False, help_text='是否新品', verbose_name='是否新品'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='market_price',
            field=models.FloatField(default=0, help_text='市场价格', verbose_name='市场价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(help_text='商品名', max_length=100, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='ship_free',
            field=models.BooleanField(default=True, help_text='是否承担运费', verbose_name='是否承担运费'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='shop_price',
            field=models.FloatField(default=0, help_text='本店价格', verbose_name='本店价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sold_num',
            field=models.IntegerField(default=0, help_text='商品销售量', verbose_name='商品销售量'),
        ),
    ]
