# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-08 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180508_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='is_deleted',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='是否删除'),
        ),
        migrations.AlterField(
            model_name='verifycode',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='更改时间'),
        ),
    ]
